apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web
          image: nginx:1.23.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
